/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedNewPostRouteImport } from './routes/_authenticated/new-post'
import { Route as AuthenticatedPostsRouteRouteImport } from './routes/_authenticated/posts/route'
import { Route as AuthenticatedPostsPublishedRouteImport } from './routes/_authenticated/posts/published'
import { Route as AuthenticatedPostsDraftRouteImport } from './routes/_authenticated/posts/draft'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNewPostRoute = AuthenticatedNewPostRouteImport.update({
  id: '/new-post',
  path: '/new-post',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPostsRouteRoute = AuthenticatedPostsRouteRouteImport.update({
  id: '/posts',
  path: '/posts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPostsPublishedRoute =
  AuthenticatedPostsPublishedRouteImport.update({
    id: '/published',
    path: '/published',
    getParentRoute: () => AuthenticatedPostsRouteRoute,
  } as any)
const AuthenticatedPostsDraftRoute = AuthenticatedPostsDraftRouteImport.update({
  id: '/draft',
  path: '/draft',
  getParentRoute: () => AuthenticatedPostsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/posts': typeof AuthenticatedPostsRouteRouteWithChildren
  '/new-post': typeof AuthenticatedNewPostRoute
  '/posts/draft': typeof AuthenticatedPostsDraftRoute
  '/posts/published': typeof AuthenticatedPostsPublishedRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/posts': typeof AuthenticatedPostsRouteRouteWithChildren
  '/new-post': typeof AuthenticatedNewPostRoute
  '/posts/draft': typeof AuthenticatedPostsDraftRoute
  '/posts/published': typeof AuthenticatedPostsPublishedRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/posts': typeof AuthenticatedPostsRouteRouteWithChildren
  '/_authenticated/new-post': typeof AuthenticatedNewPostRoute
  '/_authenticated/posts/draft': typeof AuthenticatedPostsDraftRoute
  '/_authenticated/posts/published': typeof AuthenticatedPostsPublishedRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/posts'
    | '/new-post'
    | '/posts/draft'
    | '/posts/published'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/posts'
    | '/new-post'
    | '/posts/draft'
    | '/posts/published'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/posts'
    | '/_authenticated/new-post'
    | '/_authenticated/posts/draft'
    | '/_authenticated/posts/published'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/new-post': {
      id: '/_authenticated/new-post'
      path: '/new-post'
      fullPath: '/new-post'
      preLoaderRoute: typeof AuthenticatedNewPostRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/posts': {
      id: '/_authenticated/posts'
      path: '/posts'
      fullPath: '/posts'
      preLoaderRoute: typeof AuthenticatedPostsRouteRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/posts/published': {
      id: '/_authenticated/posts/published'
      path: '/published'
      fullPath: '/posts/published'
      preLoaderRoute: typeof AuthenticatedPostsPublishedRouteImport
      parentRoute: typeof AuthenticatedPostsRouteRoute
    }
    '/_authenticated/posts/draft': {
      id: '/_authenticated/posts/draft'
      path: '/draft'
      fullPath: '/posts/draft'
      preLoaderRoute: typeof AuthenticatedPostsDraftRouteImport
      parentRoute: typeof AuthenticatedPostsRouteRoute
    }
  }
}

interface AuthenticatedPostsRouteRouteChildren {
  AuthenticatedPostsDraftRoute: typeof AuthenticatedPostsDraftRoute
  AuthenticatedPostsPublishedRoute: typeof AuthenticatedPostsPublishedRoute
}

const AuthenticatedPostsRouteRouteChildren: AuthenticatedPostsRouteRouteChildren =
  {
    AuthenticatedPostsDraftRoute: AuthenticatedPostsDraftRoute,
    AuthenticatedPostsPublishedRoute: AuthenticatedPostsPublishedRoute,
  }

const AuthenticatedPostsRouteRouteWithChildren =
  AuthenticatedPostsRouteRoute._addFileChildren(
    AuthenticatedPostsRouteRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedPostsRouteRoute: typeof AuthenticatedPostsRouteRouteWithChildren
  AuthenticatedNewPostRoute: typeof AuthenticatedNewPostRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPostsRouteRoute: AuthenticatedPostsRouteRouteWithChildren,
  AuthenticatedNewPostRoute: AuthenticatedNewPostRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
